#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export TFENV_DEBUG=1
  shift
fi

if [ -n "$TFENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "tfenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/tfenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path
    path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$TFENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${TFENV_ROOT}" ]; then
  TFENV_ROOT="${HOME}/.tfenv"
else
  TFENV_ROOT="${TFENV_ROOT%/}"
fi
export TFENV_ROOT

if [ -z "${TFENV_DIR}" ]; then
  TFENV_DIR="$PWD"
else
  [[ $TFENV_DIR == /* ]] || TFENV_DIR="$PWD/$TFENV_DIR"
  cd "$TFENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$TFENV_DIR'"
  TFENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export TFENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${TFENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

TFENV_HOOK_PATH="${TFENV_HOOK_PATH}:${TFENV_ROOT}/tfenv.d"
if [ "${bin_path%/*}" != "$TFENV_ROOT" ]; then
  # Add tfenv's own `tfenv.d` unless tfenv was cloned to TFENV_ROOT
  TFENV_HOOK_PATH="${TFENV_HOOK_PATH}:${bin_path%/*}/tfenv.d"
fi
TFENV_HOOK_PATH="${TFENV_HOOK_PATH}:/usr/local/etc/tfenv.d:/etc/tfenv.d:/usr/lib/tfenv/hooks"
for plugin_hook in "${TFENV_ROOT}/plugins/"*/etc/tfenv.d; do
  TFENV_HOOK_PATH="${TFENV_HOOK_PATH}:${plugin_hook}"
done
TFENV_HOOK_PATH="${TFENV_HOOK_PATH#:}"
export TFENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { tfenv---version
    tfenv-help
  } | abort
  ;;
-v | --version )
  exec tfenv---version
  ;;
-h | --help )
  exec tfenv-help
  ;;
* )
  command_path="$(command -v "tfenv-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`tfenv init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "tfenv help \"$command\""
    else
      exec tfenv-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
